# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-11 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gender', models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('total_hour', models.IntegerField(verbose_name='总课时')),
                ('use_hour', models.IntegerField(verbose_name='已上课时')),
                ('total_money', models.IntegerField(verbose_name='总费用')),
                ('comment', models.CharField(max_length=80, verbose_name='简介')),
            ],
        ),
    ]
