# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-11 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='use_hour',
        ),
    ]
