# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-11 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('teachers', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(verbose_name='上课时间')),
                ('end_time', models.DateField(verbose_name='下课时间')),
                ('total_time', models.DateField(verbose_name='总时长')),
                ('title', models.CharField(max_length=60, verbose_name='标题')),
                ('class_room', models.IntegerField(verbose_name='教室')),
                ('student_money', models.IntegerField(verbose_name='学生课时费用')),
                ('teacher_money', models.IntegerField(verbose_name='教师课时费用')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.Class', verbose_name='班级')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subject.Subject', verbose_name='学科')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teachers.Teacher', verbose_name='教师')),
            ],
            options={
                'verbose_name_plural': '课程',
                'verbose_name': '课程',
                'db_table': 'tb_cour',
            },
        ),
    ]
