# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-12 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='end_time',
            field=models.DateTimeField(verbose_name='下课时间'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='start_time',
            field=models.DateTimeField(verbose_name='上课时间'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='total_time',
            field=models.IntegerField(verbose_name='总时长'),
        ),
    ]
