# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-12 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190412_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='逻辑删除'),
        ),
    ]
